name: 🔍 CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
  pull_request:

jobs:
  ci:
    name: 🔍 Lint, Format, Type & Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: 🟢 Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔍 Lint, format, type, and build checks
        run: npm run ci:check
